name: calendaroo
description: A Fancy Flutter Calendar

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^2.2.3
  flutter_redux: ^0.6.0
  rxdart: ^0.24.0
  shared_preferences: ^0.5.7
  uuid: 2.0.4
  intl: ^0.16.0
  flutter_launcher_icons: ^0.7.5
  sqflite: ^1.3.0
  path_provider: ^0.5.0+1
  scroll_to_index: ^1.0.6
  flutter_local_notifications: ^1.4.3
  url_launcher: ^5.4.11
  flutter_alert: ^0.4.0
  weather: ^1.1.1
  geolocator: ^5.3.2+2
  feather_icons_flutter: ^4.7.4
  flutter_circular_chart: ^0.1.0
  vector_math:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/
    - assets/images/
    - assets/fonts/
    - assets/resources/
    - assets/secret/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
